[package]
name = "rest_api_postgres"
version = "0.1.0"
edition = "2021"
authors = ["Viraj Shah <viraj.v.shah03@gmail.com>"]

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.4.0"
listenfd = "1.0.1"
serde = "1.0.188"
serde_json = "1.0.105"
